apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gateway
  namespace: yeahyak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-gateway
  template:
    metadata:
      labels:
        app: ai-gateway
    spec:
      imagePullSecrets:           # <<< 추가
      - name: acr-pull            # <<< 추가(위에서 만든 이름과 동일)
      containers:
      - name: ai-gateway
        image: yeahyakacr.azurecr.io/ai-gateway:1.0
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api
              key: OPENAI_API_KEY
        - name: PORT
          value: "5000"
        readinessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ai-gateway
  namespace: yeahyak
spec:
  type: LoadBalancer
  selector:
    app: ai-gateway
  ports:
  - name: http
    port: 80
    targetPort: 5000
