name: backend-build-push-deploy

on:
  push:
    branches: [ "deploy1" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        working-directory: backend
        run: chmod +x gradlew || true

      - name: Build jar (Gradle)
        working-directory: backend
        run: ./gradlew clean bootJar -x test --no-daemon --stacktrace --info

      - name: List build artifacts
        working-directory: backend
        run: ls -alh build/libs

      - name: Compute IMAGE_TAG
        id: meta
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: ACR login (az acr login)
        run: az acr login -n $ACR_NAME

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push to ACR
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.LOGIN_SERVER }}/backend:${{ steps.meta.outputs.image_tag }}
            ${{ env.LOGIN_SERVER }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: SSH into VM & update container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            LOGIN_SERVER="${{ env.LOGIN_SERVER }}"
            IMAGE="${LOGIN_SERVER}/backend:latest"
            CONTAINER_NAME="yeahyak-backend"
            HOST_BIND_IP="127.0.0.1"
            HOST_PORT="8080"
            CONTAINER_PORT="8080"

            # --- 필수 DB 시크릿 로드/검증 ---
            DB_URL="${{ secrets.DB_URL }}"
            DB_USERNAME="${{ secrets.DB_USERNAME }}"
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            if [ -z "$DB_URL" ] || [ -z "$DB_USERNAME" ] || [ -z "$DB_PASSWORD" ]; then
              echo "ERROR: DB_URL / DB_USERNAME / DB_PASSWORD GitHub Secrets가 필요합니다."
              exit 1
            fi

            # --- 스토리지 시크릿 로드/검증 ---
            BLOB_ENDPOINT="${{ secrets.BLOB_ENDPOINT }}"
            BLOB_CONTAINER="${{ secrets.BLOB_CONTAINER }}"
            BLOB_CONN_STR="${{ secrets.BLOB_CONN_STR }}"
            if [ -z "$BLOB_ENDPOINT" ] || [ -z "$BLOB_CONTAINER" ] || [ -z "$BLOB_CONN_STR" ]; then
              echo "ERROR: BLOB_ENDPOINT / BLOB_CONTAINER / BLOB_CONN_STR GitHub Secrets가 필요합니다."
              exit 1
            fi

            # ACR 로그인 (관리 사용자/토큰 사용)
            echo "${{ secrets.ACR_PASSWORD }}" | docker login "$LOGIN_SERVER" -u "${{ secrets.ACR_USERNAME }}" --password-stdin

            # 최신 이미지 pull
            docker pull "$IMAGE"

            # 기본 네트워크 없으면 생성
            docker network create yeahyak-net >/dev/null 2>&1 || true

            # 같은 이름의 컨테이너 있으면 제거
            docker rm -f "$CONTAINER_NAME" || true

            # 8080 포트 점유 중인 다른 컨테이너 제거
            INUSE_IDS=$(docker ps --format '{{.ID}} {{.Ports}}' | awk '/(0\.0\.0\.0|127\.0\.0\.1):8080->8080\/tcp/ {print $1}')
            if [ -n "$INUSE_IDS" ]; then
              echo "Port 8080 in use by: $INUSE_IDS - removing..."
              docker rm -f $INUSE_IDS || true
            fi

            # 컨테이너 재실행 (127.0.0.1:8080 -> 8080/tcp) + 프로덕션 env
            docker run -d --name "$CONTAINER_NAME" \
              --restart unless-stopped \
              --network yeahyak-net \
              -p ${HOST_BIND_IP}:${HOST_PORT}:${CONTAINER_PORT} \
              -e TZ=Asia/Seoul \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SERVER_PORT=8080 \
              -e AI_SERVICE_URL=http://yeahyak-ai:8080 \
              -e SPRING_DATASOURCE_URL="$DB_URL" \
              -e SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
              -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
              -e SPRING_JPA_HIBERNATE_DDL_AUTO=update \
              -e SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect \
              -e AZURE_STORAGE_BLOB_ENDPOINT="$BLOB_ENDPOINT" \
              -e AZURE_STORAGE_CONTAINER_NAME="$BLOB_CONTAINER" \
              -e AZURE_STORAGE_CONNECTION_STRING="$BLOB_CONN_STR" \
              "$IMAGE"

            # 이미지 청소 & 로그아웃 (옵션)
            docker image prune -f
            docker logout "$LOGIN_SERVER" || true
