name: backend-build-push-deploy

on:
  push:
    branches: [ "dev" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        working-directory: backend
        run: chmod +x gradlew || true

      - name: Build jar (Gradle)
        working-directory: backend
        run: ./gradlew clean bootJar -x test --no-daemon --stacktrace --info

      - name: List build artifacts
        working-directory: backend
        run: ls -alh build/libs

      - name: Compute IMAGE_TAG
        id: meta
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: ACR login (az acr login)
        run: az acr login -n $ACR_NAME

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push to ACR
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.LOGIN_SERVER }}/backend:${{ steps.meta.outputs.image_tag }}
            ${{ env.LOGIN_SERVER }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: SSH into VM & update container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            LOGIN_SERVER="${{ env.LOGIN_SERVER }}"
            IMAGE="${LOGIN_SERVER}/backend:latest"

            # VM에서 ACR 로그인 (admin 계정/토큰 사용)
            echo "${{ secrets.ACR_PASSWORD }}" | docker login "$LOGIN_SERVER" -u "${{ secrets.ACR_USERNAME }}" --password-stdin

            docker pull "$IMAGE"

            docker rm -f backend || true
            docker run -d --name backend \
              -p 8080:8080 \
              --restart unless-stopped \
              -e SPRING_PROFILES_ACTIVE=prod \
              "$IMAGE"

            docker image prune -f
