name: backend-build-push-deploy

on:
  push:
    branches: [ "dev" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        working-directory: backend
        run: chmod +x gradlew || true

      - name: Build jar (Gradle)
        working-directory: backend
        run: ./gradlew clean bootJar -x test --no-daemon --stacktrace --info

      - name: List build artifacts
        working-directory: backend
        run: ls -alh build/libs

      - name: Compute IMAGE_TAG
        id: meta
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: ACR login (az acr login)
        run: az acr login -n $ACR_NAME

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push to ACR
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.LOGIN_SERVER }}/backend:${{ steps.meta.outputs.image_tag }}
            ${{ env.LOGIN_SERVER }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: SSH into VM & update container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script_stop: true
          envs: TZ,SPRING_PROFILES_ACTIVE,SERVER_PORT,AI_SERVICE_URL,DB_URL,DB_USERNAME,DB_PASSWORD,BLOB_ENDPOINT,BLOB_CONTAINER,BLOB_CONN_STR
          script: |
            set -eu

            LOGIN_SERVER="${{ env.LOGIN_SERVER }}"
            IMAGE="${LOGIN_SERVER}/backend:latest"
            CONTAINER_NAME="yeahyak-backend"
            NET_NAME="yeahyak-net"
            HOST_IP="127.0.0.1"
            PORT="8080"

            for v in TZ SPRING_PROFILES_ACTIVE SERVER_PORT AI_SERVICE_URL DB_URL DB_USERNAME DB_PASSWORD BLOB_ENDPOINT BLOB_CONTAINER BLOB_CONN_STR; do
              eval "val=\${$v-}"
              [ -n "$val" ] || { echo "missing env: $v"; exit 1; }
            done

            echo "${{ secrets.ACR_PASSWORD }}" | docker login "$LOGIN_SERVER" -u "${{ secrets.ACR_USERNAME }}" --password-stdin
            docker pull "$IMAGE"

            docker network create "$NET_NAME" >/dev/null 2>&1 || true
            docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
            INUSE=$(docker ps --format '{{.ID}} {{.Ports}}' | awk '/(0\.0\.0\.0|127\.0\.0\.1):8080->8080\/tcp/ {print $1}')
            [ -n "$INUSE" ] && docker rm -f $INUSE || true

            docker run -d --name "$CONTAINER_NAME" \
              --restart unless-stopped \
              --network "$NET_NAME" \
              -p ${HOST_IP}:${PORT}:${PORT} \
              -e TZ="$TZ" \
              -e SPRING_PROFILES_ACTIVE="$SPRING_PROFILES_ACTIVE" \
              -e SERVER_PORT="$SERVER_PORT" \
              -e AI_SERVICE_URL="$AI_SERVICE_URL" \
              -e SPRING_DATASOURCE_URL="$DB_URL" \
              -e SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
              -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
              -e AZURE_STORAGE_BLOB_ENDPOINT="$BLOB_ENDPOINT" \
              -e AZURE_STORAGE_CONTAINER_NAME="$BLOB_CONTAINER" \
              -e AZURE_STORAGE_CONNECTION_STRING="$BLOB_CONN_STR" \
              "$IMAGE"

            docker image prune -f >/dev/null 2>&1 || true
            docker logout "$LOGIN_SERVER" || true
        env:
          TZ: Asia/Seoul
          SPRING_PROFILES_ACTIVE: prod
          SERVER_PORT: "8080"
          AI_SERVICE_URL: http://yeahyak-ai:8080

          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

          BLOB_ENDPOINT: ${{ secrets.BLOB_ENDPOINT }}
          BLOB_CONTAINER: ${{ secrets.BLOB_CONTAINER }}
          BLOB_CONN_STR: ${{ secrets.BLOB_CONN_STR }}
